version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: congress
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: congress
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend

volumes:
  pgdata: